version: "3.9"
services:

  fluentbit:
    image: fluent/fluent-bit:1.8
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit-parsers.conf:/fluent-bit/etc/fluent-bit-parsers.conf
      - ./credentials.json:/fluent-bit/etc/credentials.json
    environment:
      - GOOGLE_SERVICE_CREDENTIALS=/fluent-bit/etc/credentials.json
    restart: always
    network_mode: host

  shadowsocks:
    command: -v
    logging:
      driver: fluentd
    depends_on:
      - fluentbit
